TI DFA/NFA implementation
MiskinAleksandr23/TI-DFA-NFA pull request #1
Opened 2024-10-01 18:36 UTC by MiskinAleksandr23

Что то написал, вроде даже работает(и даже NFA -> DFA)

2024-10-10 15:33 UTC, virogg commented
- Алгоритмы симуляции DFA и NFA реализованы правильно и выполняют свои задачи. $(5/5)$
- Код `nfa2dfa.py` правильно реализует основные шаги алгоритма построения подмножеств и соответствует тому, что был на лекции. $(5/5)$
- Тестов _немного_, но они показывают, что алгоритмы работают корректно.  $(4.7/5)$

Всё написано лаконично и понятно!
Оценка: $⌈4.9⌉ / 5 = 5/5$

2024-10-25 09:25 UTC, katyacyfra requested changes
Норм, хотя в конвертации NFA-> DFA работаете экспонентой состояний, что на практике не самый лучший вариант (лучше идти от стартовых, постепенно строя DFA)

Тесты конвертации  NFA-> DFA надо пофиксить

2024-10-25 09:25 UTC, katyacyfra commented on README.md
> +Немного изменен формат входных данных(для обоих структур)\
Неудобно для проверки разных входов на одном и том же автомате

2024-10-25 09:25 UTC, katyacyfra commented on main.py
> +        self.assertEqual(result, dfa.execute(list(map(int, file.readlines()[-1].split()))))
:scream: всё-таки Ваш формат входа не очень удобен

2024-10-25 09:25 UTC, katyacyfra commented on main.py
> +    def test_NFAtoDFA1(self):
Так не проверяют корректность конвертации( Ну принял новый автомат какую-то ОДНУ строку, которую принимал исходный, но это еще ни о чем не говорит

2024-10-27 20:58 UTC, MiskinAleksandr23 commented
Что то исправил.
Немного поправил формат ввода, теперь там есть примеры(и функции типа createDFA) по которым можно построить DFA/NFA. Для удобства убрал тесты проверяющие первое задание, второе тестируется так: Создается рандомный NFA и строится по нему DFA. Потом проверяется на большом числе(типа 100) строк как в коде.

Можно конечно и наивно сравнивать(типа по переходам), но мне кажется сравнивать на большом числе тестов тоже ок:)

2024-11-17 14:57 UTC, katyacyfra approved these changes

2024-12-18 20:08 UTC, merged